### ISSUE TITLE
发现一个不错的表情键盘可否引入

### ISSUE THREAD

**Issue by ejiyuan** [HsuanXyz/ionic3-chat#3]
发现一个不错的表情键盘可否引入
[https://github.com/danielehrhardt/ionic3-emoji-picker](https://github.com/danielehrhardt/ionic3-emoji-picker)

**Comment by HsuanXyz** [comment]
@ejiyuan 嘿，你好。emoji 应该是大多数系统键盘自带的，我想知道你为什么会有这样的需求，我有什么我没想到的吗？

**Comment by peterfei** [comment]
@ejiyuan   正是我在别的项目要引用的，谢谢了~

**Comment by ejiyuan** [comment]
@HsuanXyz 都是国人交流方便多了不必使用蹩脚的英语了，是这样的，基本所有的社交app聊天模块都可以实现，软键盘（keyboard）与表情键盘的自由切换，微信、微博等都有自己的表情系统，如果自己弄一套太费劲，快手 使用的是 emoji表情，这个还是不错的，iOS ，安卓都支持，只需要完成 软键盘与表情键盘切换即可，这里我原本想监听系统键盘打开后，关闭 表情键盘（其实就是一个隐藏的div之类的东西，做隐藏/显示），可是，每当键盘关闭后显示表情键盘 输入框就会失去焦点，这个问题 弄了两个与 都没有办法实现 快手，微信的切换效果。

**Comment by HsuanXyz** [comment]
好的，我会尝试集成进去实现效果

**Comment by ejiyuan** [comment]
@HsuanXyz 好的谢谢~不过这个很难搞定！
