### ISSUE TITLE
Ios keyboard issue

### ISSUE THREAD

**Issue by kitkimwong** [HsuanXyz/ionic3-chat#5]
ha, guy. Good job!
But how about IOS ? I know that there are many keyboard issues in IOS.
for example: spellcheck, autocomplete and keyboard scroll issue, those issue is mentions in this ionic forum issue: 
https://forum.ionicframework.com/t/about-to-give-up-with-ionic-3-simple-native-like-chat-page-not-possible/87548/20

Would you like to take a look at that and improve you project.

Well done and good luck

Best Regards

**Comment by HsuanXyz** [comment]
@kitkimwong 
IOS there are still keyboard issues.
