### ISSUE TITLE
Problem with <emoji-picker>

### ISSUE THREAD

**Issue by gzodx** [HsuanXyz/ionic3-chat#8]
i using ionic 3 cli 3.8.0 and is saying <emoji-picker> is not a ionic tag or something it not working

**Comment by diaosilan2013** [comment]
you can reinstall ionic cliTry it again
		

		Witever Chau
	





On Sat, Aug 26, 2017 at 2:57 AM +0800, "gzodx" <notifications@github.com> wrote:












i using ionic 3 cli 3.8.0 and is saying  is not a ionic tag or something it not working

**Comment by gzodx** [comment]
i just updated it recently

**Comment by gzodx** [comment]
i just updated it recently and i tried it on cli 3.0.6 it worked

**Comment by gzodx** [comment]
Thank with all your update but it still saying "Uncaught (in promise): Error: Template parse errors: 'emoji-picker' is not a known element: 1. If 'emoji-picker' is an Angular component, then verify that it is part of this module. 2. If 'emoji-picker' is a Web Component "

what i did was to copy emoji.ts and the emoji picker components and added it to my project ,running your own independently is working good ,but on my chat app every thing is working fine only on my chat.html
<emoji-picker *ngIf="_isOpenEmojiPicker" [(ngModel)]="newmessage"> not working

**Comment by coolvasanth** [comment]
I'm also facing the same issue, does anybody found the solution for it ?
