### ISSUE TITLE
Emoji icon fill is transparent 

### ISSUE THREAD

**Issue by shaloba** [HsuanXyz/ionic3-chat#9]
Hi, by your demo the emoji is yellow and its very nice  but when i run it on my host it is transparent 

can you help me change it ? 

thanks!

**Comment by gzodx** [comment]
What device do u open it from and Wat browser cause some browser can't convert it so try it on your phone or on chrome or firefox

**Comment by HsuanXyz** [comment]
http://caniemoji.com/
